#
#	           GunPlugin
#   Highly Customizable Gun Plugin
#               v1.0.1
#

# General Settings
bulletDrop: false
cancelEvent: true
cancelPlayerDamage: true

# Bullet Settings
bullet:
  item: 'ARROW'
  particleAmount: 1
  particleDelay: 1
  projectileVisible: false
  removeAmmoAmount: 1
  
# Gun Settings
gun: 
  bulletVelocity: 3.5
  damage: 5.0
  item: 'BOW'
  recoilStanding: 0.05
  recoilCrouching: 0.01

# Gun Actions
actions:
  shoot: 'RIGHT_CLICK'
  reload: 'LEFT_CLICK'

# Sound Settings
blockHit:
  sound: 'BLOCK_ANVIL_HIT'
  volume: 1
  pitch: 100
entityHit:
  sound: 'BLOCK_BAMBOO_BREAK'
  volume: 1
  pitch: 100
gunshot: 
  sound: 'ENTITY_ARROW_SHOOT'
  volume: 3
  pitch: 100
hitMarker: 
  sound: 'BLOCK_BAMBOO_BREAK'
  volume: 1
  pitch: 100
noAmmo: 
  sound: 'UI_BUTTON_CLICK'
  volume: 1
  pitch: 100
reload: 
  sound: 'ITEM_SHIELD_BLOCK'
  volume: 1
  pitch: 100
  
# Particles
bulletParticle: 
  particle: 'ELECTRIC_SPARK'
  particleStartDelay: 2
  particleFollowTicks: 1
blockHitParticle:
  particle: 'ASH'
  amount: 100
entityHitParticle: 
  particle: 'FALLING_LAVA'
  amount: 100